project:
  type: website
  pre-render: _processing/pre_render.py
  render: 
    - index.qmd
    - gallery/project_gallery.qmd
    - gallery/*/*/*/*.qmd
    - project/*
    - python/*
    - qgis/*
    - r/*

website:
  title: "UQ Library Training Intensives"
  navbar:
    search: true
    left:
      - text: "R"
        href: r/setup.md
      - text: "QGIS"
        href: qgis/setup.md
      - text: "Python"
        href: python/setup.md
      - text: "The Project"
        href: project/details.qmd
      - text: "Project Gallery"
        href: gallery/project_gallery.qmd
      - text: "UQ Library Technology Training"
        href: https://uqlibrary.github.io/technology-training
      # - text: "**Book for Feb 2026**"
      #   href: https://studenthub.uq.edu.au/students/events/detail/5909456
  sidebar:   
    - title: "R with RStudio"
      collapse-level: 2
      contents:
        - r/setup.md
        - auto: "r/Essentials"
        - auto: "r/Advanced topics"

    - title: "QGIS"
      collapse-level: 2
      contents:
        - qgis/setup.md

    - title: "Python for Data Analysis"
      collapse-level: 2
      contents:
        - python/setup.md
        - auto: "python/Essentials"
        - auto: "python/Advanced topics"
        - python/7-your_own_data.qmd

    - title: "The Project"
      contents:
        - auto: "project/*"
    
format:
  html:
    theme: 
      - default
      - custom.scss
    toc: true
    embed-resources: false

execute:
  freeze: auto